---
title: "S* vs S*’ vs Sclinic"
author: "Chentian Jiang"
date: "2/4/2019"
output:
  pdf_document: 
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, fig.pos= "h")
source("../../utils_custom.R")
library(kableExtra)

load("../../dt_metrics.RData")
load("../../dt_hr_clinical_closest.RData")
setkey(dt_metrics, Id)
setkey(dt_hr_clinical_closest, Id)
```

```{r}
dt_hr_clinical_closest$mean_RHR %>% mean()
```


```{r}
table <- dt_metrics[, .(Id, RHR_mean, RHR_sd, )]

table <- data.frame(
  RHR = c(mean(dt_metrics$RHR_median), mean(dt_metrics$RHR_sd), mean(dt_metrics$RHR_size)),
  notRHR = c(mean(dt_metrics$notRHR_median), mean(dt_metrics$notRHR_sd), mean(dt_metrics$notRHR_size)),
  clinicRHR = c(mean(dt_hr_clinical_closest$mean_RHR), NA, NA)
)

colnames(table) <- c("Est. RHR", "Est. non-RHR", "Clinic RHR")
rownames(table) <- c("Mean Value (bpm)", "Mean SD (bpm)", "Mean Size")

kable(table, "latex") %>%
  kable_styling(position = "center")
```